apiVersion: v1
kind: Service
metadata:
  name: distribution-center-nodeport-service
spec:
  type: NodePort
  selector:
    app: distributioncenterapi
  ports:
    - name: distributioncenterapi
      protocol: TCP
      port: 80
      targetPort: 80